name: Node JS apply to EKS
on: 
    push: 
        branches: [ "main"]
    pull_request:
        branches: [ "main"]

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout stage
              uses: actions/checkout@v4
            
            - name: Install kubectl
              uses: azure/setup-kubectl@v4
              with:
               version: 'v1.24.0' # default is latest stable
              id: install

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: us-east-1

            - name: login ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
            
            - name: Build, tag, and push docker image to Amazon ECR
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: testrepo
                IMAGE_TAG: 1.1
              run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
              
            - name: Update kube config
              run: aws eks update-kubeconfig --name my-eks-cluster3 --region us-east-1
              
            - name: Deploy to EKS
              run: |
                  kubectl apply -f deployment.yaml
                  kubectl apply -f service.yaml